open Virtual_dom

let create = Vdom.Node.create_svg
let svg = create "svg"
let a = create "a"
let circle = create "circle"
let ellipse = create "ellipse"
let defs = create "defs"
let g = create "g"
let image = create "image"
let line = create "line"
let linear_gradient = create "linearGradient"
let marker = create "marker"
let mask = create "mask"
let polyline = create "polyline"
let path = create "path"
let polygon = create "polygon"
let radial_gradient = create "radialGradient"
let rect = create "rect"
let stop = create "stop"
let style = create "style"
let symbol = create "symbol"
let text = create "text"
let text_path = create "textPath"
let title = create "title"
let tspan = create "tspan"
let use = create "use"
